version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./config.yaml:/config/config.yaml
    command:
      - /app/wait-for-it.sh
      - "${REDIS_PRIMARY_ENDPOINT}:${REDIS_PORT}"
      - --timeout=60
      - --strict
      - --
      - /app/rss_sync
    restart: unless-stopped
    ports:
      - "8080:8080"
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
